.Dd $wikitdate$
.TH wikit 1 "23 Aug 2020" "4.4.0" "wikit manual"
.Dt wikit 1
.Os

.SH NAME
wikit - wikipedia summaries from the command line

.SH SYNOPSIS
.B wikit
.B <QUERY>
.OP -abdD
.OP --link
.OP --lang <LANG>
.OP --browser <BROWSER>
.OP --line <NUM>
.[page]

.SH DESCRIPTION
.B wikit
is a tool for quickly querying wikipedia from your terminal.

.SH OPTIONS
Quotes are recommended, though not required, if QUERY consists of multiple words.
.PP
Available flags:
.Bl -tag -width -indent
.It -a, --all
Print all sections of the article, recommended to pipe into a reader e.g. less
.It -b
Open Wikipedia article in default browser
.It -d
Open disambiguation CLI menu
.It -D
Open disambiguation page in browser
.It --link
Print a link to the full article after the summary
.It --l, --lang <LANG>
Specify language;
.Ar LANG
is an HTML ISO language code
.It --browser <BROWSER>
Open article in specific
.Ar BROWSER
.It --line <NUM>
Set line wrap length to
.Ar NUM
(minimum 15)
.It -v, --version
Print installed version number
.It -n, --name
Print the program name: wikit
.El
.Pp

.SH CONFIGURATION
To change the default language, edit ~/.config/configstore/wikit.json

.SH EXIT STATUS
Wikit exits with an exit code of 0 unless one of the following happens, in which case it will exit with a 1:
.Bl -tag -width -indent
.It - The language code provided is unrecognized
.It - The line length provided is invalid
.It - There were no arguments passed
.El
.Pp
